import React, { useState } from 'react';
import {
    CheckCircle, Share2, Download, Printer, Shield,
    FileText, Clock, User, AlertTriangle, History, PenTool, Send, RotateCcw
} from 'lucide-react';
import { useApp, ROLES, STATUS } from '../context/AppContext';
import Button from '../components/Button';
import styles from './ReviewApproval.module.css';

const AUDIT_LOG = [
    { time: '14:30:12', message: 'Report auto-generated by OrthoReport AI v4.2', type: 'normal' },
    { time: '14:32:05', message: 'Finding #1 reviewed by clinician', type: 'normal' },
    { time: '14:33:18', message: 'Finding #2 confirmed', type: 'normal' },
    { time: '14:34:42', message: 'Recommendation #1 modified', type: 'warning' },
    { time: '14:35:10', message: 'Conflict acknowledged for Recommendation #2', type: 'warning' },
];

const ReviewApproval = () => {
    const {
        currentRole,
        reportStatus,
        hasPermission,
        approveReport,
        requestRevision,
        submitForReview,
        isLocked
    } = useApp();

    const [approved, setApproved] = useState(reportStatus === STATUS.APPROVED);

    const canApprove = hasPermission('canApproveReport');
    const canRequestRevision = hasPermission('canRequestRevision');
    const canSubmit = hasPermission('canSubmitForReview');

    const handleApprove = () => {
        setApproved(true);
        approveReport();
    };

    const handleRequestRevision = () => {
        requestRevision();
    };

    const handleSubmitForReview = () => {
        submitForReview();
    };

    // Lab view - Submit for Review
    if (currentRole === ROLES.LAB) {
        return (
            <div className={styles.container}>
                <div className={styles.card}>
                    <div className={styles.successHeader}>
                        <div className={`${styles.iconWrapper} ${styles.iconPending}`}>
                            <Send size={40} />
                        </div>
                        <h2 className={styles.title}>Ready to Submit</h2>
                        <p className={styles.description}>
                            Review the report summary below and submit for clinical review when ready.
                        </p>
                    </div>

                    <div className={styles.summarySection}>
                        <div className={styles.summaryTitle}>Report Summary</div>
                        <div className={styles.summaryRow}>
                            <span className={styles.rowLabel}>
                                <AlertTriangle size={14} /> Total Findings
                            </span>
                            <span className={styles.rowValue}>3 detected</span>
                        </div>
                        <div className={styles.summaryRow}>
                            <span className={styles.rowLabel}>
                                <FileText size={14} /> Scan Quality
                            </span>
                            <span className={styles.rowValue}>Excellent (98/100)</span>
                        </div>
                        <div className={styles.summaryRow}>
                            <span className={styles.rowLabel}>
                                <Clock size={14} /> Time Spent
                            </span>
                            <span className={styles.rowValue}>12 minutes</span>
                        </div>
                    </div>

                    {(reportStatus === STATUS.DRAFT || reportStatus === STATUS.REVISED) && (
                        <button
                            className={styles.approvalButton}
                            onClick={handleSubmitForReview}
                        >
                            <Send size={20} />
                            Submit for Clinical Review
                        </button>
                    )}

                    {reportStatus === STATUS.IN_REVIEW && (
                        <div className={styles.pendingBanner}>
                            <Clock size={20} />
                            <span>Report is pending clinical review</span>
                        </div>
                    )}
                </div>
            </div>
        );
    }

    // Assistant view - Read only with revision request
    if (currentRole === ROLES.ASSISTANT) {
        return (
            <div className={styles.container}>
                <div className={styles.card}>
                    <div className={styles.successHeader}>
                        <div className={`${styles.iconWrapper} ${reportStatus === STATUS.APPROVED ? styles.iconSuccess : styles.iconPending}`}>
                            {reportStatus === STATUS.APPROVED ? <CheckCircle size={40} /> : <Shield size={40} />}
                        </div>
                        <h2 className={styles.title}>
                            {reportStatus === STATUS.APPROVED ? 'Report Approved' : 'Pending Doctor Approval'}
                        </h2>
                        <p className={styles.description}>
                            {reportStatus === STATUS.APPROVED
                                ? 'This report has been finalized by the supervising doctor.'
                                : 'This report is awaiting approval from the supervising doctor.'}
                        </p>
                    </div>

                    <div className={styles.summarySection}>
                        <div className={styles.summaryTitle}>Report Summary</div>
                        <div className={styles.summaryRow}>
                            <span className={styles.rowLabel}>
                                <AlertTriangle size={14} /> Total Findings
                            </span>
                            <span className={styles.rowValue}>3 (1 Confirmed, 2 Dismissed)</span>
                        </div>
                        <div className={styles.summaryRow}>
                            <span className={styles.rowLabel}>
                                <FileText size={14} /> Primary Treatment
                            </span>
                            <span className={styles.rowValue}>Restorative (UL6)</span>
                        </div>
                        <div className={styles.summaryRow}>
                            <span className={styles.rowLabel}>
                                <User size={14} /> Approval Authority
                            </span>
                            <span className={styles.rowValue}>Dr. Michael Anderson, DDS</span>
                        </div>
                    </div>

                    {reportStatus !== STATUS.APPROVED && canRequestRevision && (
                        <Button
                            variant="secondary"
                            onClick={handleRequestRevision}
                            icon={<RotateCcw size={16} />}
                            style={{ width: '100%', marginBottom: 'var(--spacing-md)' }}
                        >
                            Request Revision
                        </Button>
                    )}
                </div>
            </div>
        );
    }

    // Doctor view - Full approval flow
    return (
        <div className={styles.container}>
            <div className={styles.card}>
                <div className={styles.successHeader}>
                    <div className={`${styles.iconWrapper} ${approved || isLocked() ? styles.iconSuccess : styles.iconPending}`}>
                        {approved || isLocked() ? <CheckCircle size={40} /> : <Shield size={40} />}
                    </div>
                    <h2 className={styles.title}>
                        {approved || isLocked() ? 'Report Finalized' : 'Ready for Approval'}
                    </h2>
                    <p className={styles.description}>
                        {approved || isLocked()
                            ? 'This report has been digitally signed, archived, and is ready for distribution.'
                            : 'Please review the summary below and apply your digital signature to finalize.'}
                    </p>
                </div>

                <div className={styles.summarySection}>
                    <div className={styles.summaryTitle}>Report Summary</div>
                    <div className={styles.summaryRow}>
                        <span className={styles.rowLabel}>
                            <AlertTriangle size={14} /> Total Findings
                        </span>
                        <span className={styles.rowValue}>3 (1 Confirmed, 2 Dismissed)</span>
                    </div>
                    <div className={styles.summaryRow}>
                        <span className={styles.rowLabel}>
                            <FileText size={14} /> Primary Treatment
                        </span>
                        <span className={styles.rowValue}>Restorative (UL6)</span>
                    </div>
                    <div className={styles.summaryRow}>
                        <span className={styles.rowLabel}>
                            <User size={14} /> Approval Authority
                        </span>
                        <span className={styles.rowValue}>Dr. Michael Anderson, DDS</span>
                    </div>
                    <div className={styles.summaryRow}>
                        <span className={styles.rowLabel}>
                            <Clock size={14} /> Report Date
                        </span>
                        <span className={styles.rowValue}>October 24, 2024</span>
                    </div>
                </div>

                {!approved && !isLocked() ? (
                    <>
                        <div
                            className={styles.signatureBox}
                            onClick={handleApprove}
                        >
                            <div className={styles.signatureLabel}>Click to apply digital signature</div>
                            <PenTool size={24} color="var(--color-text-disabled)" />
                        </div>

                        <div className={styles.buttonRow}>
                            <Button
                                variant="secondary"
                                onClick={handleRequestRevision}
                                icon={<RotateCcw size={16} />}
                            >
                                Request Revision
                            </Button>
                            <button
                                className={styles.approvalButton}
                                onClick={handleApprove}
                                style={{ flex: 1 }}
                            >
                                <Shield size={20} />
                                Approve & Finalize
                            </button>
                        </div>
                    </>
                ) : (
                    <>
                        <div className={`${styles.signatureBox} ${styles.signed}`}>
                            <div className={styles.signatureLabel}>Digitally Signed By</div>
                            <div className={styles.signatureName}>Dr. Michael Anderson</div>
                            <div className={styles.signatureTime}>October 24, 2024 at 14:38:22 PST</div>
                        </div>

                        <div className={styles.actionGrid}>
                            <div className={styles.actionCard}>
                                <div className={styles.actionIcon}>
                                    <Download size={20} />
                                </div>
                                <div className={styles.actionText}>
                                    <h4>Download PDF</h4>
                                    <p>Get printable report</p>
                                </div>
                            </div>
                            <div className={styles.actionCard}>
                                <div className={styles.actionIcon}>
                                    <Share2 size={20} />
                                </div>
                                <div className={styles.actionText}>
                                    <h4>Share with Patient</h4>
                                    <p>Send via email or portal</p>
                                </div>
                            </div>
                            <div className={styles.actionCard}>
                                <div className={styles.actionIcon}>
                                    <Printer size={20} />
                                </div>
                                <div className={styles.actionText}>
                                    <h4>Print Record</h4>
                                    <p>Print for physical records</p>
                                </div>
                            </div>
                            <div className={styles.actionCard}>
                                <div className={styles.actionIcon}>
                                    <Shield size={20} />
                                </div>
                                <div className={styles.actionText}>
                                    <h4>Verify Signature</h4>
                                    <p>Check authenticity</p>
                                </div>
                            </div>
                        </div>
                    </>
                )}

                <div className={styles.auditTrail}>
                    <h4 className={styles.auditTitle}>
                        <History size={16} /> Audit Trail
                    </h4>
                    <div className={styles.auditLog}>
                        {AUDIT_LOG.map((entry, index) => (
                            <div key={index} className={styles.logEntry}>
                                <span className={styles.logTime}>[2024-10-24 {entry.time}]</span>
                                <span className={`${styles.logMessage} ${entry.type === 'warning' ? styles.warning : ''}`}>
                                    {entry.message}
                                </span>
                            </div>
                        ))}
                        {(approved || isLocked()) && (
                            <div className={styles.logEntry}>
                                <span className={styles.logTime}>[2024-10-24 14:38:22]</span>
                                <span className={`${styles.logMessage} ${styles.success}`}>
                                    ✓ Report approved and digitally signed by User ID: 8821
                                </span>
                            </div>
                        )}
                    </div>
                </div>
            </div>
        </div>
    );
};

export default ReviewApproval;
